name: Build and publish

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
          - os: ubuntu-latest
          - os: windows-2019
          - os: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Prepare dist
        shell: bash
        run: bin/download.sh

      - name: Build for Linux
        if: matrix.os == 'ubuntu-latest'
        run: bin/compile-linux.sh

      - name: Build for Windows
        if: matrix.os == 'windows-latest'
        shell: bash
        run: bin/compile-windows-64.sh

      - name: Build for Windows 2019
        if: matrix.os == 'windows-2019'
        shell: bash
        run: bin/compile-windows-32.sh

      - name: Build for macOS
        if: matrix.os == 'macos-latest'
        shell: bash
        run: bin/compile-macos.sh

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*
          file_glob: true
          tag: ${{ github.ref }}
